### ISSUE TITLE
FSP Proposal Feedback

### ISSUE THREAD

**Issue by AAlfarho** [ttillotson/TipTopTomes#3]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md).
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Each App specific MVP needs the following bullet points are added:
    + Adequate styling
    + Smooth, bug-free navigation
    + Seeded with info to demonstrate this feature

- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments:
Great job on the definition of your MVP's and the estimated time. This section is complete!
As for the order of the MVP's, lets discuss this tomorrow on how to address MVP's that rely on each other to be completed.

# Database Schema
- [x] Contains correct datatypes
  - [x] WIll the `published` column on `book`be a string or datetime? Same for the create/updated_at.
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments:
Great job on the database schema, indexes and references look appropriate.

# Routes

- [x] Routes accurately reflect MVPs and Component Hierarchy
- [x] Covers the frontend functionality of the site through routes that match to the wireframes
- [x] Contains the following sections: API Endpoints(Backend), and Frontend Routes
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
  - [x] Will we be able to see other users bookshelves? If no, then we don't really need the _:userId_ on the frontend route, right? If we do, disregard this comment and check.
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments:
Kudos for the attention to detail in your backend routes, they look really solid!

# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased, (check the image_url key)
- [x] All keys within the values in the state are accessible in the schema (Ex: if you create a `imgUrl` key in the state, make sure your database also has a column that contains an `img_url`)
- [x] Correctly formatted
    - [x] Sample state is rendered with 3 back ticks before and after. This will display the state as a code block instead of a giant line of text
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [ ] `ui` (if needed)
          - [ ] UI will be used as the slice for all things UI, the perfect example would be loading spinners, however, if nothing comes to your mind at the moment, there is no need to add it.
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
    
# Comments:
- [x] We need to decide whether users will have imageUrl or not, I would suggest for time being to go with a placeholder image, as _user profile_ is not part of the MVP.
- [x] The state for entities.users looks a bit funky, take a look at the inline comments.
   ```javascript
    users: {
         5: {
        { // extra curly brace here?
          id: 4, // typo here, it should be 5, right?
          username: realreelname,
          email: reallyreall@fakeemailsRus.com,
          img_url: '/path/to/user/img',
          bookshelf: 45 // will users have more than 1 shelf?
      }
    },
   ```

# Component Hierarchy with Wireframes

- [x] All routes listed in the routes wiki page is also listed in the component hierarchy
- [x] Each component, if necessary, has route, state, and other components it renders [example](https://github.com/appacademy/bluebird/wiki/component-hierarchy)
- [x] Necessary components are wrapped in a container
- [x] Correctly formatted
    - [x] Bullet point hierarchy
    - [x] Component names are displayed with `inline coding text` (backticks)
- [x] Wireframes included
  - [x] Every component listed in the component hierarchy wiki page has at least one wireframe
  - [x] Every MVPs listed on the MVP wiki page has at least one wireframe
  - [x] Every route listed on the route wiki page has at least one wireframe
  - [x] Contains Containers
  - [x] Correctly formatted
    - [x] Wireframe images display on the page
    - [x] Every wireframe has a header title

## Comments:
- [x] Ads are not part of any MVP I would suggest leaving them as a bonus.
- [ ] There are certain features/components of the site that are not part of the MVP'; as we should not have a dummy, non-functional placeholders, let's not have anything that is not MVP on our layout, that will include:
   + SiteSpecificItem
   + AdvertisementItem
   + Feed
   + RecommendedBooks
   + BookTriviaContainer
 Reason for taking them out is not only that they are not MVP's but in order for them to look & behave properly, they would have to rely on a heavily seeded DB, which then again steers us in a bonus direction. However that leaves us with an empty home page, let's discuss this tomorrow on how we can address this.

Amazing attention to detail and planning on the proposal, kudos !
Please check the missing checkboxes as you update your proposal.

**Comment by ttillotson** [comment]
Hey, went over your revisions. Below are my updates/comments/concerns:

Would I include bonus MVPs at the bottom of my current MVP list or move it elsewhere, such as Milestone/Issue?
- [ ] Bottom of MVP
- [ ] Milestone/Issue
Note: I will move ads and User img_url to bonus. 

#### User Profile/Bookshelves
User profiles will be their bookshelf. I feel it would remove a lot fo intuitive functionality to not be able to click on other users, easiest way to fix this is to route clicks to their combined bookshelf since this has the most relevant information that is already keyed into my system. With that in mind, users will have multiple shelves (currently reading, want to read, have read, plus the ability to create a new one) and the combined shelf will be a fetched joins table of all their shelves. 
With this implementation it makes the most sense to have the shelves associated to their owners and let the database keep its own count for them, yes?
- [ ] Yes
- [ ] No
