### ISSUE TITLE
PA MVP Review: User Auth

### ISSUE THREAD

**Issue by ttillotson** [ttillotson/TipTopTomes#6]
- [x] Account Creation
- [x] Login/Logout
- [x] Guest/Demo User
- [x] Adequate Styling
- [x] Smooth, bug-free navigation

**Comment by AAlfarho** [comment]
Amazing attention to detail on the styling, I had to double check I was not on the actual site.
There a couple of issues we need to address before closing this MVP.

- [ ] There are no errors being displayed to the user when invalid credentials are used to log in, or when trying to create a user with incorrect data.
- [ ] Are we issuing `event.preventDefaut()` when submitting the form for creating new users?, our URL is appending a question mark as result`/?#/`.
- [ ] After login out a user, the Nav bar still show `My Books`, is this expected? GoodReads redirects you to a new page. What do you think about redirecting users to `/` and protecting all routes but `/`.

Assign this issue back to me once the updates addressing these issues are live in Heroku.

**Comment by AAlfarho** [comment]
After discussing a couple of the issues here described, we have agreed that the following MVP's will handle redirecting and default routes.

I will close this MVP, however, I **strongly** suggest that after we are done with the MVP's we give the login/signup errors display a styling overhaul. 

![screen shot 2018-04-09 at 9 15 56 am](https://user-images.githubusercontent.com/1103663/38509876-09d800b6-3bd8-11e8-9403-622f835af442.png)

We will have to find and alternative to the error display for sign up.

**Comment by ttillotson** [comment]
Would it be better to just redirect them to the corresponding page with the errors displayed? 
e.g. Failed sign-in redirects to formal sign in form; same for sign up
