### ISSUE TITLE
PA MVP: Books

### ISSUE THREAD

**Issue by ttillotson** [ttillotson/TipTopTomes#7]
- [x] Users can view single books and details: Publication Specs, Reviews
- [x] Sufficient Seeds
- [x] Adequate Styling
- [x] Smooth, bug-free navigation

**Comment by ttillotson** [comment]
Hey, I'm assigning this now before the Reviews are properly formatted because they have their own MVP. Relevant information is there for the books and reviews, but reviews are unstyled.

**Comment by ttillotson** [comment]
Sample Index:  https://www.goodreads.com/genres/fiction
Sample Show: https://www.goodreads.com/book/show/5.Harry_Potter_and_the_Prisoner_of_Azkaban

**Comment by AAlfarho** [comment]
Great job on the books MVP, the seeding gives the site a whole new feeling, kudos !!

This MVP is now closed.
