### ISSUE TITLE
PA MVP Review: Reviews

### ISSUE THREAD

**Issue by ttillotson** [ttillotson/TipTopTomes#9]
- [x] Tied to both the book and user
- [x] Can be created and destroyed
- [x] Links to Reviewer
- [x] Has a rating
- [x] Sufficient seeds to illustrate feature

**Comment by AAlfarho** [comment]
A couple of issues before closing this MVP.

 - [ ] There seems to be an issue editing a review (deleting looks fine). If update will not be available let's remove the links.
     + Logged in as demo user.
     + Went to book id 118.
     + Click `Edit your Review`,  a new page is rendered with no content. Same issue if I scroll all the way down to the review and hit `update.`.
 - [ ] Reviews should be displayed in a most-recent order, that way we would be able to see right away the review with just created.

Feel free to mark the checkboxes yourself after addressing them. Assign this issue back to me once the updates are live in Heroku.

**Comment by ttillotson** [comment]
Not sure what was goin on with edit, works now though. If you have any advise on delaying the spinner falling away I'd be grateful!

**Comment by AAlfarho** [comment]
Good job on the reviews, the addition of the spinner was great.

The functionality required for the MVP is completed, however, there is one detail I would like you to track under a new issue.

- [ ] Ideally, reviews should be sorted from most recent, if we create or update a review, that review should be the first one to be displayed, that way the user can have instant feedback on the new/updated review.

Kudos!

**Comment by ttillotson** [comment]
They are...
